name: Java Build EXE 

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build with Maven
      run: mvn clean package

    - name: List Target Directory
      run: ls -l target

    - name: Download Launch4j
      run: |
        wget https://sourceforge.net/projects/launch4j/files/launch4j-3/3.50/launch4j-3.50-linux-x64.tgz/download -O launch4j-linux.tgz
        tar -xzf launch4j-linux.tgz

    - name: Fix Line Endings for Launch4j Script
      run: |
        sed -i 's/\r$//' launch4j/launch4j  # Convert CRLF to LF

    - name: Create EXE
      run: |
        if [ -f "myapp.xml" ]; then
          chmod +x launch4j/launch4j
          ./launch4j/launch4j myapp.xml || { echo "Launch4j failed"; exit 1; }
        else
          echo "myapp.xml does not exist."
          exit 1
        fi

    - name: List Launch4j Directory
      run: ls -l launch4j

    - name: Upload EXE artifact
      uses: actions/upload-artifact@v4
      with:
        name: myapp-executable
        path: ./launch4j/myapp.exe

    - name: Commit and Push EXE to Repository
      env:
        GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git remote set-url origin https://x-access-token:${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/Talha-Abdurehman/Quantum-Quasar.git
        git add ./launch4j/myapp.exe 
        git commit -m "Add new version of myapp.exe"
        git push || echo "No changes to commit."
