name: Build Java EXE

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '11' # Specify the version of Java you need

    - name: Build with Maven
      run: mvn clean package # Adjust if you're using Gradle or another build tool

    - name: Create EXE
      run: |
        # Use Launch4j or similar tool to wrap your JAR into an EXE
        # Example command, adjust according to your setup
        launch4j myapp.xml

    - name: Upload EXE artifact
      uses: actions/upload-artifact@v2
      with:
        name: myapp-executable
        path: path/to/your/exe/myapp.exe # Adjust the path accordingly
