name: Build and Package Java Application

on:
  push:
    branches:
      - main  # Run on pushes to the main branch
  workflow_dispatch:  # Allow manual triggering of the workflow

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '17'  # Set the Java version as per your project

    - name: Build Java Application
      run: |
        mvn clean package # Adjust to your build tool (e.g., Maven or Gradle)

    - name: Download Launch4j Installer
      run: |
        curl -L -o launch4j-installer.exe "https://downloads.sourceforge.net/project/launch4j/files/launch4j-3/3.50/launch4j-3.50.exe"

    - name: Verify Launch4j Installer
      run: |
        if (!(Test-Path .\launch4j-installer.exe)) {
          Write-Error "Launch4j installer download failed."
          exit 1
        }

    - name: Install Launch4j
      run: |
        Start-Process -FilePath ".\launch4j-installer.exe" -ArgumentList "/VERYSILENT" -NoNewWindow -Wait

    - name: Verify Launch4j Installation
      run: launch4j --version

    - name: Create Executable with Launch4j
      run:
