name: Build and Package Java Application
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Download Launch4j
      run: |
        Invoke-WebRequest -Uri "https://downloads.sourceforge.net/project/launch4j/launch4j-3.14-win32.zip" -OutFile "launch4j.zip"
        Expand-Archive -Path "launch4j.zip" -DestinationPath "launch4j"
        echo "${{ github.workspace }}\launch4j" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

    - name: Build with Maven (if using Maven)
      run: mvn clean package
      # Remove this step if you're not using Maven

    - name: Create .exe with Launch4j
      run: |
        $launch4jPath = "${{ github.workspace }}\launch4j\launch4j.exe"
        & $launch4jPath "${{ github.workspace }}\launch4j-config.xml"

    - name: Upload .exe as artifact
      uses: actions/upload-artifact@v3
      with:
        name: game-executable
        path: ${{ github.workspace }}\target\output.exe  # Adjust this path to match your actual output path
