name: Java Build EXE 

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Using updated version

    - name: Set up JDK
      uses: actions/setup-java@v3  # Already using v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build with Maven
      run: mvn clean package

    - name: List Target Directory
      run: ls -l target  # Check for generated JAR files

    - name: Download Launch4j
      run: |
        wget https://sourceforge.net/projects/launch4j/files/launch4j-3/3.14/launch4j-3.14-linux-x64.tgz/download -O launch4j-linux.tgz
        tar -xzf launch4j-linux.tgz
        ls -l  # List contents of current directory for debugging

    - name: Create EXE
      run: |
        if [ -f "myapp.xml" ]; then
          chmod +x launch4j/launch4j
          ./launch4j/launch4j myapp.xml  # Adjust path to your config file
        else
          echo "myapp.xml does not exist."
          exit 1
        fi

    - name: List Launch4j Directory
      run: ls -l launch4j  # Check if myapp.exe was created

    - name: Upload EXE artifact
      uses: actions/upload-artifact@v4
      with:
        name: myapp-executable
        path: /home/runner/work/Quantum-Quasar/Quantum-Quasar/myapp.exe  # Update this path based on previous checks or keep it as ./launch4j/your-output.exe if not changing output name.

    - name: Commit and Push EXE to Repository
      env:
        GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git remote set-url origin https://x-access-token:${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/Talha-Abdurehman/Quantum-Quasar.git
        git add myapp.exe
        git commit -m "Add new version of myapp.exe"
        git push
