name: Build and Package Java Application

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Verify Chocolatey Installation
      run: choco --version

    - name: Install or Reinstall Launch4j
      run: choco install launch4j -y --force

    - name: Add Launch4j to PATH
      run: |
        $env:Path += ";C:\ProgramData\chocolatey\lib\launch4j\tools"
        echo $env:Path

    - name: Verify Launch4j Installation
      run: launch4j --version

    # Fallback: Download Launch4j Portable
    - name: Download Launch4j Portable
      if: failure()
      run: |
        Invoke-WebRequest -Uri "https://downloads.sourceforge.net/project/launch4j/launch4j-3.14-win32.zip" -OutFile "launch4j.zip"
        Expand-Archive -Path "launch4j.zip" -DestinationPath "launch4j"
        $env:Path += ";${{ github.workspace }}\launch4j"
        echo $env:Path

    - name: Create .exe with Launch4j
      run: |
        launch4j\launch4j.exe --config launch4j-config.xml

    - name: Upload .exe as artifact
      uses: actions/upload-artifact@v3
      with:
        name: game-executable
        path: path/to/output.exe
