name: Build Java EXE

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build with Maven
      run: mvn clean package

    - name: Download Launch4j
      run: |
        wget https://github.com/lukeshu/launch4j/releases/download/3.14/launch4j-3.14-linux.tar.gz
        tar -xzf launch4j-3.14-linux.tar.gz
        chmod +x launch4j-3.14/launch4j

    - name: Create EXE
      run: |
        ./launch4j-3.14/launch4j myapp.xml  # Adjust the path to your config file

    - name: Upload EXE artifact
      uses: actions/upload-artifact@v4
      with:
        name: myapp-executable
        path: path/to/your/exe/myapp.exe  # Adjust the path accordingly
