name: Build Java EXE

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build with Maven
      run: mvn clean package

    - name: List Target Directory
      run: ls -l target  # Check for generated JAR files

    - name: Download Launch4j
      run: |
        wget https://sourceforge.net/projects/launch4j/files/launch4j-3/3.14/launch4j-3.14-linux-x64.tgz/download -O launch4j-linux.tgz
        tar -xzf launch4j-linux.tgz
        ls -l  # List contents of current directory for debugging

    - name: Create EXE
      run: |
        if [ -f "myapp.xml" ]; then
          chmod +x launch4j/launch4j
          ./launch4j/launch4j myapp.xml  # Adjust path to your config file
        else
          echo "myapp.xml does not exist."
          exit 1
        fi

    - name: Move EXE to Out Folder
      run: |
        mkdir -p out
        mv ./launch4j/myapp.exe out/

    - name: List Out Directory
      run: ls -l out  # Verify that the .exe file is in the out directory

    - name: Upload EXE artifact
      uses: actions/upload-artifact@v4
      with:
        name: myapp-executable
        path: out/myapp.exe
